### PR TITLE
When specifying the extra_config_sections as an array

### PR DESCRIPTION
**Pull request by ralfbosz**
the entries are set on multiple lines instead of joined on the same line

also fixed an error in the example which was missing some }

### CODE REVIEW

**Comment by ralfbosz** [comment]
took some more changes, but travisci is green

**Comment by traylenator** [comment]
We can't just change the test here in the .robocop.yml , the file is templated in.

**Comment by ralfbosz** [comment]
I've reversed the .rubocop.yml to the "master-branch" version, but still shows as diff in the PR.

The change was made to make it pass the Travis CI, don't have everything installed on my current machine to do local testing...

**Comment by ralfbosz** [comment]
#2.9 failed fails, no very clear error, seems more like a TravisCI error then in code.

**Comment by ralfbosz** [comment]
I've updated my PR, only changed what was needed for this function...

**Pull request merged**
