### PR TITLE
Added ssl_bump and sslproxy_cert_error support.

### PR DESCRIPTION
**Pull request by jadestorm**
Howdy!  This PR adds support for the ssl_bump and sslproxy_cert_error types.  (very similar to some of the other types)  I am afraid I have not actually tested the spec test components of the PR, so please let me know if they fail miserably.

### CODE REVIEW

**Comment by traylenator** [comment]
@jadestorm they do indeed fail :-)

**Comment by jadestorm** [comment]
Dooh!  Ok let me take a look.  =)

**Comment by jadestorm** [comment]
Much better.  Was doing something stupid with the concat fragment naming.  I'm going to squish all of those commits together, just a sec.

**Comment by jadestorm** [comment]
There we go.  Ok!  Should be good to go now, let me know if you need me to make any more adjustments!

**Comment by traylenator** [comment]
Okay, if you can just resolve the conflicts.

**Comment by jadestorm** [comment]
Oh sure!  I see some work has been done since I submitted this.  =)  Just a moment --

**Comment by jadestorm** [comment]
Ok resolved!

**Pull request merged**
