### PR TITLE
added debian 9 param defaults

### PR DESCRIPTION
**Pull request by ssanden**
debian 9 defaults

### CODE REVIEW

**Comment by traylenator** [comment]
Hi @ekohl 
Can you update the metadata.yaml file also for the new platform - thanks.

**Comment by traylenator** [comment]
Pleaes remove the needs-work tag when you would like me to take a look again.

**Comment by ekohl** [comment]
> Hi @ekohl
> Can you update the metadata.yaml file also for the new platform - thanks.

I think you mean @traylenator 

> Please remove the needs-work tag when you would like me to take a look again.

I can do that since I'm a member but @ssanden can't.

**Comment by traylenator** [comment]
I meant @ssanden

**Comment by ssanden** [comment]
> Can you update the metadata.yaml file also for the new platform - thanks.

done

**Comment by wyardley** [comment]
I'll merge this.

I was going to look into adding a Debian 9 box in modulesync so we could run acceptance tests, but doesn't seem to be one yet at:
https://vagrantcloud.com/puppetlabs
Couldn't get the Docker one to work on a quick try, but will give it another try later.

**Pull request merged**
