### PR TITLE
Added compatiblity to Debian 8 and prepared module to support multipl…

### PR DESCRIPTION
**Pull request by fluser**
…e params for different OS

No breaking changes.

### CODE REVIEW

**Comment by bastelfreak** [comment]
Hi @fluser. thanks for the PR! Could you please rebase against master? That will make the tests work again.

**Comment by fluser** [comment]
Hi @bastelfreak 
I'm not shure if rebase worked. I hope so ;-)

**Comment by bastelfreak** [comment]
I think it worked. Can you take a look at the puppet-lint errors? You can ping us in #voxpupuli on freenode if you need any help.

**Comment by bastelfreak** [comment]
I'm not really sure what is broken here. My browser dies when I try to open the travis log :cry:

**Comment by fluser** [comment]
I think, it's a problem with the facts. I try to solve this.

**Comment by bastelfreak** [comment]
Please take a look at [rspec-puppet-facts](https://github.com/mcanevet/rspec-puppet-facts), this gem will take care of mocking the facts. As an example you can take a look at our [zabbix module](https://github.com/voxpupuli/puppet-zabbix/blob/master/spec/classes/userparameter_spec.rb#L7-L13).

**Comment by alexjfisher** [comment]
I've created https://github.com/voxpupuli/puppet-squid/pull/19 to enabled rspec-puppet-facts across all spec tests.

**Comment by alexjfisher** [comment]
@fluser I've rebased your changes into a new PR https://github.com/voxpupuli/puppet-squid/pull/20 and added a couple of tweaks.  Your changes are still credited to you in the new commits.  I hope you're OK with that?

**Pull request closed without merging**
